general {
  lock_cmd = pidof hyprlock || hyprlock
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
  on_unlock_cmd=systemctl --user restart ssh-tunnel.service || hyprctl dispatch dpms on
  inhibit_sleep=3
}

listener {
  on-resume=brightnessctl -r
  on-timeout=brightnessctl -s set 30
  timeout=180
}

listener {
  timeout=300                                 # 5min
  on-timeout=playerctl -a status | grep -q -v "Playing" && loginctl lock-session            # lock screen when timeout has passed
}

listener {
    timeout=330                                                                                  # 5.5min
    on-timeout=playerctl -a status | grep -q -v "Playing" &&  hyprctl dispatch dpms off                            # screen off when timeout has passed
    on-resume=hyprctl dispatch dpms on && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

listener {
  on-timeout=playerctl -a status | grep -q -v "Playing" && systemctl suspend
  timeout=1800
}
